version: '3.5'

services:
  cqdg-data-submission-postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data_submission
      POSTGRES_USER: cqdg
      POSTGRES_PASSWORD: password
    ports:
      - 5532:5432
  adminer:
    image: adminer
    ports:
      - 5180:8080
